apiVersion: v1
kind: Pod
metadata:
  name: flask-image
  labels:
    app: flask_app
spec:
  containers:
    - name: flask
      image: timu71/docker_repo_timu:flaskapp_sql
      imagePullPolicy: Always
      ports:
      - name: flask
        containerPort: 5000
        protocol: TCP

