apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: flaskapp
  selector:
    app: flask_app
  type: NodePort