name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd flask-app
        docker build -t flask-app-test-gh:latest .
    - name: Archive Docker Image
      uses: actions/upload-artifact@v2
      with:
        name: flask-app-test-download
        path: |
          docker save flask-app-test-gh:latest > flask-app-test-gh.tar
          gzip -f flask-app-test-gh.tar
          flask-app-test-gh.tar.gz
          
  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: flask-app-test-download
        path: .
    - name: Load Docker Image
      run: |
        gzip -df flask-app-test-gh.tar.gz
        docker load -i flask-app-test-gh.tar
