name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cd app
          docker build -t flask-app-test:latest .
      - name: Save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: flask-app-image
          path: |
            docker save flask-app-test:latest > flask-app-test.tar
            gzip -f flask-app-test.tar
            flask-app-test.tar.gz

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: flask-app-image
      - name: Load Docker image
        run: |
          gzip -d flask-app-test.tar.gz
          docker load -i flask-app-test.tar
