name: Docker Image CI

on:
  push:
    branches: [ "prod", "dev" ]
  pull_request:
    branches: [ "prod", "dev" ]

jobs:
    build:
        permissions:
            id-token: write
            contents: read

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
          with:
              role-to-assume: arn:aws:iam::233276167072:role/rest-api-gh-role
              aws-region: eu-central-1
              role-session-name: ci-session-${{ github.event.repository.name }}
              # audience: arn:aws:iam::233276167072:oidc-provider/token.actions.githubusercontent.com
        - name: Get current branch
          run: |
            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
            echo $BRANCH_NAME
            echo ${{ env.BRANCH_NAME }}
        - name Build the Docker image
          run: |
            cd flask-app
            docker build -t flask-app-${{ env.BRANCH_NAME }}-gh:latest .
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
        - name: push the Docker image
          run: |
            docker tag flask-app-${{ env.BRANCH_NAME }}-gh:latest 233276167072.dkr.ecr.eu-central-1.amazonaws.com/tf-training-${{ env.BRANCH_NAME }}-ecr-python:0.0.2-SNAPSHOT
            docker push  233276167072.dkr.ecr.eu-central-1.amazonaws.com/tf-training-${{ env.BRANCH_NAME }}-ecr-python:0.0.2-SNAPSHOT

