name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd flask-app
        docker build -t flask-app-test-gh:latest .
    - name: Archive Docker Image
      run: |
        docker save flask-app-test-gh:latest > flask-app-test-gh.tar
        gzip -f flask-app-test-gh.tar
    - uses: actions/upload-artifact@v2
      with:
        name: flask-app-test-download
        path: flask-app-test-gh.tar.gz
